chore: detect files exists is-skip-commitlint.js

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -6,8 +6,19 @@
 # Date: 2019.01.20
 #
 
+js=.githooks/is-skip-commitlint.js
+if [ ! -f $js ]; then
+  tsc -p .githooks/tsconfig.json
+
+  if [ ! -f $js ]; then
+    echo -e "File not found! is-skip-commitlint.js"
+    exit 1
+  fi
+fi
+
+
 branch=$( git branch | grep \* | cut -d ' ' -f2 )
-node ./.githooks/is-skip-commitlint.js $1 "$branch"
+node "$js" $1 "$branch"
 #ts-node -P tsconfig.cjs.json ./.githooks/is-skip-commitlint.ts $1 "$branch"
 
 code=$?
